# Generated by Django 6.0.1 on 2026-05-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_is_on_sale_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gross_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
