# Generated by Django 6.0.1 on 2026-05-07 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_gross_weight_product_height_product_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimension_unit',
            field=models.CharField(choices=[('cm', 'Centímetros'), ('m', 'Metros')], default='cm', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
