# Generated by Django 6.0.1 on 2026-05-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_dimension_unit_alter_product_gross_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimension_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('m', 'm')], default='cm', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='length_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('m', 'm')], default='cm', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='width_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('m', 'm')], default='cm', max_length=2),
        ),
    ]
