# Generated by Django 6.0.1 on 2026-04-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='userprofile/'),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('customer', 'Cliente'), ('admin', 'Administrador')], default='customer', max_length=20),
        ),
    ]
