# Generated by Django 6.0.1 on 2026-06-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0002_alter_ticket_order_id_chatsession_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Activa o desactiva los respaldos automaticos.', verbose_name='Respaldo activo')),
                ('interval_minutes', models.PositiveIntegerField(default=1440, help_text='Frecuencia del respaldo en minutos. Ejemplos: 1 = cada minuto, 60 = cada hora, 1440 = diario, 10080 = semanal.', verbose_name='Intervalo (minutos)')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de Respaldo',
                'verbose_name_plural': 'Configuracion de Respaldo',
            },
        ),
    ]
