# Generated by Django 6.0.1 on 2026-04-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='igtf_tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
