# Generated by Django 6.0.1 on 2026-05-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_igtf_tax_order_payment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
