# Generated by Django 6.0.1 on 2026-05-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_fecha_entrega_alter_order_status_transportista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exception_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_exception',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en_camino', 'En camino'), ('entregado', 'Entregado')], default='New', max_length=20),
        ),
    ]
