# Generated by Django 6.0.1 on 2026-05-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_exception_reason_order_is_exception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente de Pago'), ('review', 'En Revisión'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nuevo'), ('Processing', 'Procesando'), ('Assigned', 'Asignado'), ('In Transit', 'En Camino'), ('Delivered', 'Entregado'), ('Completed', 'Completado'), ('Cancelled', 'Cancelado')], default='New', max_length=20),
        ),
    ]
