# Generated by Django 6.0.1 on 2026-05-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
