# Generated by Django 6.0.1 on 2026-05-21 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_coupon_order_discount_amount_order_referral_rewarded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nuevo'), ('Processing', 'Procesando'), ('Prepared', 'Pedido Preparado'), ('Assigned', 'Asignado'), ('Picked Up', 'Recogido'), ('In Transit', 'En Camino'), ('Nearby', 'Cerca del Destino'), ('Delivered', 'Entregado'), ('Completed', 'Completado'), ('Cancelled', 'Cancelado'), ('Failed Attempt', 'Intento Fallido')], default='New', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('prepared', 'Pedido Preparado'), ('picked_up', 'Recogido por Transportista'), ('in_transit', 'En Camino'), ('nearby', 'Cerca del Destino'), ('delivered', 'Entregado'), ('failed_attempt', 'Intento de Entrega Fallido')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_deli_order_i_667c62_idx'), models.Index(fields=['status'], name='orders_deli_status_2966c5_idx')],
            },
        ),
    ]
