# Generated by Django 6.0.1 on 2026-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status_deliverycheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliverycheckpoint',
            name='status',
            field=models.CharField(choices=[('picked_up', 'Recogido por Transportista'), ('in_transit', 'En Camino'), ('nearby', 'Cerca del Destino'), ('delivered', 'Entregado'), ('failed_attempt', 'Intento de Entrega Fallido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nuevo'), ('Processing', 'Procesando'), ('Assigned', 'Asignado'), ('Picked Up', 'Recogido'), ('In Transit', 'En Camino'), ('Nearby', 'Cerca del Destino'), ('Delivered', 'Entregado'), ('Completed', 'Completado'), ('Cancelled', 'Cancelado'), ('Failed Attempt', 'Intento Fallido')], default='New', max_length=20),
        ),
    ]
